# Copyright 2019-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
# _checkenv and run_tests defined in ptf/run/<target>/Makefile
# which imports this file

PTF_FILTER ?=

all: fabric fabric-bng fabric-spgw fabric-int fabric-spgw-int

fabric: _checkenv
ifndef TEST
	$(eval TEST = all ^spgw ^int ^bng ^dth ^xconnect ^p4rt $(PTF_FILTER))
endif
	$(call run_tests,fabric,$(TEST))

fabric-bng: _checkenv
ifndef TEST
	$(eval TEST = all ^spgw ^int ^xconnect ^p4rt $(PTF_FILTER))
endif
	$(call run_tests,fabric-bng,$(TEST))

fabric-spgw: _checkenv
ifndef TEST
	$(eval TEST = all ^int ^bng ^dth ^p4rt $(PTF_FILTER))
endif
	$(call run_tests,fabric-spgw,$(TEST))

fabric-spgw-int: _checkenv
ifndef TEST
	$(eval TEST = all ^bng ^dth ^p4rt $(PTF_FILTER))
endif
	$(call run_tests,fabric-spgw-int,$(TEST))

fabric-int: _checkenv
ifndef TEST
	$(eval TEST = all ^spgw ^bng ^dth ^p4rt $(PTF_FILTER))
endif
	$(call run_tests,fabric-int,$(TEST))
