# Copyright 2019-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache v2

exports_files(["LICENSE"])

filegroup(
    name = "fabric_p4test_stratum_p4_test_files",
    srcs = [
        "tests/ptf/base_test.py",
        "tests/ptf/port_map.veth.json",
        "tests/ptf/ptf_runner.py",
    ],
)
