#!/usr/bin/env bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

set -e

# Tester image
# Contains PTF and tvutils libraries, as well as P4RT, gNMI, and TV Python bindings
#TESTER_DOCKER_IMG="stratumproject/testvectors:ptf-py3"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

# shellcheck source=ptf/run/bmv2/base.sh
source "${DIR}/base.sh"
testerRunName=tester-${randomNum}
echo "*** Starting ${testerRunName}..."

# Do not attach stdin if running in an environment without it (e.g., Jenkins)
it=$(test -t 0 && echo "-it" || echo "-t")
docker run --name "${testerRunName}" "${it}" --rm --privileged \
    --network "container:${stratumBmV2RunName}" \
    -e P4C_OUT="${P4C_OUT}" \
    -e PTF_FILTER="${PTF_FILTER}" \
    -v "${FABRIC_TNA_ROOT}":/fabric-tna \
    --entrypoint /fabric-tna/ptf/run/bmv2/start_test.sh \
    "${TESTER_DOCKER_IMG}" \
    "${@}"
