#!/usr/bin/env bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
FP4TEST_ROOT="${DIR}"/../..
FABRIC_TNA="${FP4TEST_ROOT}"/..

# PTF tester image
# TODO: depend on a simple tester image (this image contains also BMv2)
FP4TEST_DOCKER_IMG=${FP4TEST_DOCKER_IMG:-onosproject/fabric-p4test:latest}
SDE_VERSION=${SDE_VERSION:-9.2.0}
# Use image sha to pin a specific stratum_bmv2 build and have reproducible runs.
# We could instrument CI to test on both a stable version and the latest one.
STRATUM_BF_DOCKER_IMG=${STRATUM_BF_DOCKER_IMG:-stratumproject/stratum-bf:9.2.0}

if [[ -z "${FABRIC_TNA}" ]]; then
    echo "ERROR: FABRIC_TNA env not defined"
    exit 1
fi

if [[ -z "${SDE_DOCKER_IMG}" ]]; then
    echo "ERROR: SDE_DOCKER_IMG env not defined"
    exit 1
fi

if [[ -z "${STRATUM_BF_DOCKER_IMG}" ]]; then
    echo "ERROR: STRATUM_BF_DOCKER_IMG env not defined"
    exit 1
fi

if [[ -z "${SDE_VERSION}" ]]; then
    echo "ERROR: SDE_VERSION env not defined"
    exit 1
fi

fabricProfile=$1
if [ -z "${fabricProfile}" ]; then
    echo "fabric-tna profile is not set"
    exit 1
fi

if [ "${fabricProfile}" = "all" ]; then
    echo "Testing 'all' profiles is not supported on tofino-model"
    exit 1
fi
echo "*** Testing profile '${fabricProfile}'..."

detectedSdeVer=$(docker run --rm "${SDE_DOCKER_IMG}" tofino-model --version | cut -d' ' -f2 | cut -d '-' -f1)
echo "*** Detected BF SDE version ${detectedSdeVer} (tofino-model), required ${SDE_VERSION}..."
if [ "${detectedSdeVer}" != "${SDE_VERSION}" ]; then
    echo "ERROR: SDE version mismatch"
    exit 1
fi

# Find Tofino compiled artifacts
sdeVer_=$(echo "${SDE_VERSION}" | tr . _) # Replace dots with underscores
P4C_OUT=${FABRIC_TNA}/src/main/resources/p4c-out/${fabricProfile}/tofino/mavericks_sde_${sdeVer_}
echo "*** Using P4 compiler output in ${P4C_OUT}..."
if [ ! -f "${P4C_OUT}"/pipe/tofino.bin ]; then
    echo "ERROR: missing tofino.bin in ${P4C_OUT}"
    exit 1
fi

# Fix a name for each container so we can stop them
randomNum=${RANDOM}
tmRunName=tofino-model-${randomNum}
stratumBfRunName=stratum-bf-${randomNum}
testerRunName=fabric-p4test-${randomNum}

function stop() {
    set +e
    echo "*** Stopping ${stratumBfRunName}..."
    docker stop -t0 ${stratumBfRunName} > /dev/null 2>&1
    docker cp ${stratumBfRunName}:/tmp/workdir "${DIR}"/log/stratum-bf > /dev/null 2>&1
    docker rm ${stratumBfRunName} > /dev/null 2>&1

    echo "*** Stopping ${tmRunName}..."
    docker stop -t0 ${tmRunName} > /dev/null 2>&1
    docker cp ${tmRunName}:/tmp/workdir "${DIR}"/log/tofino-model > /dev/null 2>&1
    docker rm ${tmRunName} > /dev/null 2>&1
}
trap stop EXIT

function wait_for() {
    echo "*** Wait for ${1} to start up (port ${2})..."
    docker run --rm --network "container:${1}" toschneck/wait-for-it "localhost:${2}" -t "${3}"
}

rm -rf "${DIR}"/log
mkdir "${DIR}"/log

# Run Tofino Model
# Replace dots with underscores to match pipeconf name
echo "*** Starting ${tmRunName} (from ${SDE_DOCKER_IMG})..."
docker run --name ${tmRunName} -d -t --privileged \
    -v "${DIR}":/workdir -w /workdir \
    -v "${P4C_OUT}":/p4c-out \
    --entrypoint ./tm_entrypoint.sh \
    "${SDE_DOCKER_IMG}"
sleep 5

# Run stratum_bf
echo "*** Starting ${stratumBfRunName} (from ${STRATUM_BF_DOCKER_IMG})..."
docker run --name ${stratumBfRunName} -d --privileged \
    --network "container:${tmRunName}" \
    -v "${DIR}":/workdir -w /workdir \
    --entrypoint ./stratum_entrypoint.sh \
    "${STRATUM_BF_DOCKER_IMG}"
sleep 5
wait_for ${stratumBfRunName} 28000 60

echo "*** Starting ${testerRunName}..."
docker run --name ${testerRunName} -it --privileged --rm \
    --network "container:${tmRunName}" \
    -v "${FP4TEST_ROOT}":/fabric-p4test \
    -v "${P4C_OUT}":/p4c-out \
    --entrypoint /fabric-p4test/run/tm/start_test.sh \
    "${FP4TEST_DOCKER_IMG}" \
    ${@}
