#!/usr/bin/env bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

set -eu -o pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
# shellcheck source=ptf/run/tm/base.sh
source "${DIR}/base.sh"
testerRunName=tester-${randomNum}

echo "*** Starting ${testerRunName}..."
# Do not attach stdin if running in an environment without it (e.g., Jenkins)
it=$(test -t 0 && echo "-it" || echo "-t")
# shellcheck disable=SC2068
docker run --name "${testerRunName}" "${it}" --privileged --rm \
    --network "container:${tmRunName}" \
    -v "${FABRIC_TNA_ROOT}":/fabric-tna \
    -e P4C_OUT="${P4C_OUT}" \
    -e PTF_FILTER="${PTF_FILTER}" \
    --entrypoint /fabric-tna/ptf/run/tm/start_test.sh \
    "${TESTER_DOCKER_IMG}" \
    ${@}
