#!/usr/bin/env bash


TREX_CONFIG=${TREX_CONFIG:-trex-config-4ports.yaml}


docker run --name "${testerRunName}" "${it}" --rm \
    -v "${FP4TEST_ROOT}":/fabric-p4test \
    -v "${P4C_OUT}":/p4c-out \
    -e PTF_FILTER="${PTF_FILTER}" \
    -e TREX_SERVER_ADDR="${TREX_SERVER_ADDR}" \
    -e TREX_CONFIG="${TREX_CONFIG}" \
    -e SWTICH_ADDR="${SWTICH_ADDR}" \
    --entrypoint /fabric-p4test/run/flirt/start_test.sh \
    "${TESTER_DOCKER_IMG}" \
    ${@}
