#!/usr/bin/env bash

set -e

# Tester image
# Contains PTF and tvutils libraries, as well as P4RT, gNMI, and TV Python bindings
TESTER_DOCKER_IMG=stratumproject/testvectors:ptf@sha256:32241613c6b0fb56cd9ddb753df31c7355492a1d0d1b0b535efa227f717e44d0
SDE_VERSION=${SDE_VERSION:-9.2.0}

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
FP4TEST_ROOT="${DIR}"/../..
FABRIC_TNA="${FP4TEST_ROOT}"/..

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
ROOT_DIR=${DIR}/../..

if [[ -z "${FABRIC_TNA}" ]]; then
    echo "ERROR: FABRIC_TNA env not defined"
    exit 1
fi
if [[ -z "${SDE_VERSION}" ]]; then
    echo "ERROR: SDE_VERSION env not defined"
    exit 1
fi
fabricProfile=$1
if [ -z "${fabricProfile}" ]; then
    echo "fabric profile is not set"
    exit 1
fi

# Find Tofino compiled artifacts
sdeVer_=$(echo "${SDE_VERSION}" | tr . _) # Replace dots with underscores
#P4C_OUT=${FABRIC_TNA}/src/main/resources/p4c-out/${fabricProfile}/stratum_bfrt/montara_sde_${sdeVer_}
P4C_OUT=${FABRIC_TNA}/src/main/resources/p4c-out/${fabricProfile}/stratum_bfrt/mavericks_sde_${sdeVer_}

echo "*** Using P4 compiler output in ${P4C_OUT}..."
if [ ! -f "${P4C_OUT}"/pipe/tofino.bin ]; then
    echo "ERROR: missing tofino.bin in ${P4C_OUT}"
    exit 1
fi

# Clean up old logs (if any)
rm -rf "${DIR}"/log
mkdir "${DIR}"/log

rnd=${RANDOM}

# tester
# Run and show log
testerRunName=tester-${rnd}
echo "*** Starting ${testerRunName} with ${TESTER_DOCKER_IMG}..."
# Do not attach stdin if running in an environment without it (e.g., Jenkins)
it=$(test -t 0 && echo "-it" || echo "-t")
docker run --name ${testerRunName} ${it} --privileged --rm \
    -v "${ROOT_DIR}":/fabric-p4test \
    -v "${P4C_OUT}":/p4c-out \
    "${TESTER_DOCKER_IMG}" \
    bash /fabric-p4test/run/tv/start_test.sh "${FABRIC_PROFILE}" ${@}
