#!/usr/bin/env python3
# Copyright 2021-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

# Sample QoS configuration to be used with gen-stratum-qos-config.py

# Maximum number of buffer cells, depends on ASIC SKU/revision:
# - TOFINO_32D, revision A0: 266240
# - TOFINO_32D, revision B0: 266240
# - TOFINO_32Q, revision B0: 266240
# - TOFINO_64Q, revision A0: 286720
max_cells: 266240

# Percentage of buffer cells allocated to each traffic class. The sum should be 100.
pool_allocations:
  control: 1
  realtime: 9
  elastic: 80
  besteffort: 9
  # We leave a portion of the buffer unassigned for queues that don't have a pool (yet). Example of
  # such queues are those for the recirculation port, cpu port, etc.
  unassigned: 1

# The available bandwidth dedicated to Control traffic is divided in "slots". Each slot has a
# maximum rate and burst (in packets of the given MTU). A slice can use one or more slots (by
# appropriately configuring meters in the ingress pipe).
control_slot_count: 50
control_slot_rate_pps: 100
control_slot_burst_pkts: 10
control_mtu_bytes: 1500

# List of maximum shaping rates for Real-Time queues, one per slice requesting such service.
realtime_max_rates_bps:
  - 45000000 # 45 Mbps
  - 30000000 # 30 Mbps
  - 25000000 # 25 Mbps

# Maximum amount of time that a Real-Time queue can burst at the port speed.
# Used to limit delay for Elastic queues.
realtime_max_burst_s: 0.005 # 5 ms

# List of minimum guaranteed rates for Elastic queues, one per slice requesting such service.
elastic_min_rates_bps:
  - 100000000 # 100 Mbps
  - 200000000 # 200 Mbps

# List of switch ports for which we want to configure queues.
# - descr: description of the port purpose
# - rate_bps: port speed in bps
# - is_shaping_enabled: true if rate is enforced using shaping, false if it is the channel speed.
#     TODO: implement shaping configuration
# - queue_count: number of queues assigned to the port
# - sdk_ports: list of SDK port numbers (DP_ID) with this configuration
ports:
  - descr: Base station
    rate_bps: 1000000000 # 1 Gbps
    is_shaping_enabled: false
    queue_count: 8
    sdk_ports:
      - 36
      - 37
      - 38
      - 39
  - descr: Servers
    sdk_ports:
      - 260
      - 268
    rate_bps: 40000000000 # 40 Gbps
    is_shaping_enabled: false
    queue_count: 32
