# Copyright 2019-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0
# _checkenv and run_tests defined in fabric-p4test/<target>/Makefile
# which imports this file

PTF_FILTER ?=

all: fabric fabric-bng fabric-upf fabric-int fabric-upf-int

fabric: _checkenv
ifndef TEST
	$(eval TEST = all ^upf ^int ^bng ^dth ^xconnect ^p4rt ^int-dod $(PTF_FILTER))
endif
	$(call run_tests,fabric,$(TEST))

fabric-bng: _checkenv
ifndef TEST
	$(eval TEST = all ^upf ^int ^xconnect ^p4rt ^int-dod $(PTF_FILTER))
endif
	$(call run_tests,fabric-bng,$(TEST))

fabric-upf: _checkenv
ifndef TEST
	$(eval TEST = all ^int ^bng ^dth ^p4rt ^int-dod $(PTF_FILTER))
endif
	$(call run_tests,fabric-upf,$(TEST))

fabric-upf-int: _checkenv
ifndef TEST
	$(eval TEST = all ^bng ^dth ^p4rt ^int-dod $(PTF_FILTER))
endif
	$(call run_tests,fabric-upf-int,$(TEST))

fabric-int: _checkenv
ifndef TEST
	$(eval TEST = all ^upf ^bng ^dth ^p4rt ^int-dod $(PTF_FILTER))
endif
	$(call run_tests,fabric-int,$(TEST))
