#!/usr/bin/env bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
set -eu -o pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
PTF_ROOT="${DIR}"/../..
FABRIC_TNA_ROOT="${PTF_ROOT}"/..
# shellcheck source=.env
source "${FABRIC_TNA_ROOT}"/.env
export TREX_PARAMS="--trex-address ${TREX_ADDR} \
                    --trex-config /fabric-tna/ptf/run/hw/trex-config/4-ports-with-l2.yaml \
                    --force-restart"
export PORT_MAP="/fabric-tna/run/hw/port_map.trex.json"
export PTF_DIR="/fabric-tna/tests/linerate"
# shellcheck source=ptf/run/hw/base.sh
# shellcheck disable=SC2068
exec bash "${DIR}/base.sh" ${@}
