#!/usr/bin/env bash
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0
set -eu -o pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
export TREX_PARAMS="--trex-address ${TREX_ADDRESS} \
                    --trex-config /fabric-tna/run/hw/trex-config/4-ports-with-l2.yaml"
export PORT_MAP="/fabric-tna/run/hw/port_map.trex.json"
export PTF_DIR="/fabric-tna/tests/linerate"
# shellcheck source=ptf/run/hw/base.sh
exec bash "${DIR}/base.sh"
